export type Product = {
  id: string;
  name: string;
  category: 'boulangerie' | 'viennoiserie' | 'patisserie' | 'sandwich';
  description: string;
  price: number;
  image: string;
  allergenes?: string[];
};

export const products: Product[] = [
  // ── Boulangerie ───────────────────────────────────────────────────────────
  {
    id: '1',
    name: 'Baguette Tradition',
    category: 'boulangerie',
    description: 'Croustillante et dorée, fermentation naturelle sur 24h',
    price: 1.30,
    image: '/products/BaguetteTradition.jpg',
    allergenes: ['gluten'],
  },
  {
    id: '2',
    name: 'Pain de campagne',
    category: 'boulangerie',
    description: 'Pain rustique au levain, mie alvéolée et croûte épaisse',
    price: 3.40,
    image: '/products/Pain_de_campagne.png',
    allergenes: ['gluten'],
  },
  {
    id: '3',
    name: 'Pain aux céréales',
    category: 'boulangerie',
    description: 'Mélange harmonieux de graines et céréales complètes',
    price: 3.80,
    image: '/products/Pain_au_cereales.png',
    allergenes: ['gluten', 'sesame'],
  },
  {
    id: '4',
    name: 'Pain complet',
    category: 'boulangerie',
    description: 'Farine complète, riche en fibres, idéal pour la santé',
    price: 3.20,
    image: '/products/pain_complet.png',
    allergenes: ['gluten'],
  },
  {
    id: '5',
    name: 'Pain de mie',
    category: 'boulangerie',
    description: 'Moelleux et légèrement brioché, parfait pour les toasts',
    price: 4.00,
    image: '/products/Pain_de_mie.png',
    allergenes: ['gluten', 'lait'],
  },
  {
    id: '6',
    name: 'Fougasse provençale',
    category: 'boulangerie',
    description: 'Pain plat aux olives et herbes de Provence',
    price: 3.50,
    image: '/products/fougasse_provencale.png',
    allergenes: ['gluten'],
  },
  // ── Viennoiserie ─────────────────────────────────────────────────────────
  {
    id: '7',
    name: 'Croissant',
    category: 'viennoiserie',
    description: 'Feuilletage croustillant au beurre AOP Charentes-Poitou',
    price: 1.50,
    image: '/products/Croissant.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '8',
    name: 'Croissant aux amandes',
    category: 'viennoiserie',
    description: 'Croissant garni de crème d\'amandes et amandes effilées',
    price: 2.20,
    image: '/products/Croissant_aux_amandes.png',
    allergenes: ['gluten', 'lait', 'oeufs', 'fruits_a_coque'],
  },
  {
    id: '9',
    name: 'Pain au chocolat',
    category: 'viennoiserie',
    description: 'Deux barres de chocolat noir 64% dans un feuilletage beurré',
    price: 1.60,
    image: '/products/Pain_au_chocolat.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '10',
    name: 'Pain au raisin',
    category: 'viennoiserie',
    description: 'Spirale de pâte feuilletée, crème pâtissière et raisins secs',
    price: 1.90,
    image: '/products/Pain_au_raisin.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '11',
    name: 'Brioche dorée',
    category: 'viennoiserie',
    description: 'Moelleuse et parfumée, riche en beurre et en oeufs',
    price: 4.50,
    image: '/products/Brioche_doree.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '12',
    name: 'Chausson aux pommes',
    category: 'viennoiserie',
    description: 'Compote de pommes maison dans un feuilletage doré',
    price: 1.80,
    image: '/products/Chausson_pommes.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  // ── Pâtisserie ───────────────────────────────────────────────────────────
  {
    id: '13',
    name: 'Tarte au citron',
    category: 'patisserie',
    description: 'Crème au citron meringuée sur pâte sablée',
    price: 4.80,
    image: '/products/Tarte_au_citron.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '14',
    name: 'Tarte aux fraises',
    category: 'patisserie',
    description: 'Fraises fraîches sur crème pâtissière, pâte sucrée maison',
    price: 5.20,
    image: '/products/Tarte_au_fraises.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '15',
    name: 'Tarte normande',
    category: 'patisserie',
    description: 'Tarte aux pommes et crème normande sur pâte brisée',
    price: 4.20,
    image: '/products/tarte_normande.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '16',
    name: 'Éclair au chocolat',
    category: 'patisserie',
    description: 'Pâte à choux garnie de crème au chocolat, glaçage fondant',
    price: 3.90,
    image: '/products/Eclair.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '17',
    name: 'Flan pâtissier',
    category: 'patisserie',
    description: 'Crème ferme à la vanille sur pâte brisée, cuit au four',
    price: 3.50,
    image: '/products/Flan_patissier.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '18',
    name: 'Millefeuille',
    category: 'patisserie',
    description: 'Trois couches de feuilletage et crème pâtissière vanillée',
    price: 4.50,
    image: '/products/Millefeuille.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '19',
    name: 'Paris-Brest',
    category: 'patisserie',
    description: 'Pâte à choux pralinée aux noisettes du Piémont',
    price: 4.20,
    image: '/products/Paris_Brest.png',
    allergenes: ['gluten', 'lait', 'oeufs', 'fruits_a_coque'],
  },
  {
    id: '20',
    name: 'Fraisier',
    category: 'patisserie',
    description: 'Génoise, crème mousseline à la vanille et fraises fraîches',
    price: 5.50,
    image: '/products/fraisier.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '21',
    name: 'Galette des rois',
    category: 'patisserie',
    description: 'Feuilletage croustillant fourré à la crème d\'amandes',
    price: 18.00,
    image: '/products/Galette_des_rois.png',
    allergenes: ['gluten', 'lait', 'oeufs', 'fruits_a_coque'],
  },
  {
    id: '22',
    name: 'Religieuse',
    category: 'patisserie',
    description: 'Double choux garnis de crème pâtissière et glaçage fondant',
    price: 4.00,
    image: '/products/Religieuse.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '23',
    name: 'Saint-Honoré',
    category: 'patisserie',
    description: 'Choux caramélisés, crème chiboust et chantilly maison',
    price: 5.80,
    image: '/products/Saint-Honore.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '24',
    name: 'Opéra',
    category: 'patisserie',
    description: 'Biscuit joconde, ganache chocolat et crème au café',
    price: 5.00,
    image: '/products/Opera.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  {
    id: '25',
    name: 'Cake',
    category: 'patisserie',
    description: 'Cake moelleux aux fruits confits ou au citron',
    price: 12.00,
    image: '/products/Cake.png',
    allergenes: ['gluten', 'lait', 'oeufs'],
  },
  // ── Sandwich ─────────────────────────────────────────────────────────────
  {
    id: '26',
    name: 'Sandwich',
    category: 'sandwich',
    description: 'Sandwich sur pain maison avec garniture du jour',
    price: 5.50,
    image: '/products/Sandwich.png',
    allergenes: ['gluten', 'lait'],
  },
  {
    id: '27',
    name: 'Panini',
    category: 'sandwich',
    description: 'Pain ciabatta grillé, fromage fondu et garniture chaude',
    price: 6.00,
    image: '/products/Panini.png',
    allergenes: ['gluten', 'lait'],
  },
  {
    id: '28',
    name: 'Pizza',
    category: 'sandwich',
    description: 'Pizza artisanale à la tomate et mozzarella, garniture du jour',
    price: 4.50,
    image: '/products/Pizza.png',
    allergenes: ['gluten', 'lait'],
  },
];

export const categories = [
  { id: 'all', label: 'Tous nos produits' },
  { id: 'boulangerie', label: 'Boulangerie' },
  { id: 'viennoiserie', label: 'Viennoiserie' },
  { id: 'patisserie', label: 'Pâtisserie' },
  { id: 'sandwich', label: 'Snacking' },
] as const;
